name: fp_tekber_kel8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.18.1
  firebase_core: ^2.18.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.14
  equatable: ^2.0.5
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_auth: ^4.17.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
  assets:
    - assets/images/lemon_squash.jpg
    - assets/images/matcha_latte.jpg
    - assets/images/mango.jpg
    - assets/images/espresso.jpg
    - assets/images/caramel_macchiato.jpg
    - assets/images/background.png
    - assets/images/edo.jpg
    - assets/images/zikrul.jpg
    - assets/images/nida.jpg
    - assets/images/ghina.jpg