// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOiUeKS2CX_3Y6w8U7SkZFSoq2MMlFGs8',
    appId: '1:196532977484:web:835cbb5d9ec43bc6c199e9',
    messagingSenderId: '196532977484',
    projectId: 'fptekberkel8',
    authDomain: 'fptekberkel8.firebaseapp.com',
    storageBucket: 'fptekberkel8.firebasestorage.app',
    measurementId: 'G-8FNS27FER0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhO8hFn639ug47OELwcVqIlBSuk-wkcI',
    appId: '1:196532977484:android:6314f25b844d1843c199e9',
    messagingSenderId: '196532977484',
    projectId: 'fptekberkel8',
    storageBucket: 'fptekberkel8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOiUeKS2CX_3Y6w8U7SkZFSoq2MMlFGs8',
    appId: '1:196532977484:web:7f1b83099e7d45cec199e9',
    messagingSenderId: '196532977484',
    projectId: 'fptekberkel8',
    authDomain: 'fptekberkel8.firebaseapp.com',
    storageBucket: 'fptekberkel8.firebasestorage.app',
    measurementId: 'G-RSVK4869FB',
  );
}
